mglantz/ansible-roadshow

- labs/lab-1/README.md
Fixed some spelling errors and added a small chapter about SSH identities since I noticed a few people having issues with it during class.
> Edits to Lab-1 spelling and added a command for SSH identity

- content/tower-install.yml
add user to wheel group and enable passwordless sudo
> passwordless sudo

- labs/lab-1/README.md
https://github.com/mglantz/ansible-roadshow/issues/18
> fix issue 18, ansible hosts file format

- labs/lab-1/README.md
https://github.com/mglantz/ansible-roadshow/issues/24
> Updated ansible version

- labs/lab-2/README.md
- labs/lab-6/README.md
maintenence -> maintenance
developmen -> development
> Fix some minor typos

- labs/lab-5/README.md
found by a student in lab at copenhagen
> fixing missing ansible_host=

- labs/lab-7/README.md
https://github.com/ansible/awx is not an image
> Fix link to AWX github repository

- labs/lab-8/README.md
Signed-off-by: Bruno Thomsen <bruno.thomsen@gmail.com>
> lab-8: minor typo fix

- labs/lab-7/README.md
add a clarification regarding tower-cli usage.
> clarifications about tower-cli tool

- labs/lab-9/README.md
add --check for dry-run of ansible-playbook command.
> add --check parameter

- labs/lab-8/README.md
- mypassword should not be handled by git
- nginxinc.nginx role shouldn't be part of our git repo
> Add .gitignore to avoid pushing unwanted files to git

- labs/lab-7/README.md
> Update lab-7 README.md

- labs/lab-7/README.md
Not obvious how to log in. Got help and wanted to add the info.
> Document tower-cli user login

- labs/lab-7/README.md
Misplaced reference til GitHub while the project was created in GitLab
> GitLab reference fixed in lab 7

- labs/lab-9/README.md
testing scripts will fail due to vaults and no password given when running the tests
> Add --vault-password-file mypassword to testing scripts

- labs/lab-7/README.md
> another GitHub/GitLab fix

- labs/lab-10/README.md
> missing : for emoji!

- labs/lab-9/README.md
[Molecule](https://molecule.readthedocs.io/en/latest/) is a nice framework to help testing Ansible roles. I think it's worth mentioning it even if not part of the workshop.
If you are interested I could try to setup a small example, but it does require some setup that depends on the chosen driver.
> Add link to Molecule framework for testing

- labs/lab-5/README.md
The instructions says: `Do so by creating a file named .mypassword and put the password in the file.`
> rename mypassword -> .mypassword to match the instructions in lab 5

- labs/lab-0/README.md
- labs/lab-1/README.md
- labs/lab-2/README.md
> Fix some typos

- labs/lab-1/README.md
> Minor cosmetic change

- labs/lab-3/README.md
Ansible command output:
```
[student@ip-172-31-16-26 work]$ ansible-playbook -i hosts site.yml
PLAY [Install Wildfly] **********************************************************************************************************************************************************************************************************************
TASK [Gathering Facts] **********************************************************************************************************************************************************************************************************************
ok: [wildfly1]
ok: [wildfly2]
TASK [include_role : wildflyapp] ********************************************************************************************************************************************************************** …
```
> Updating README.md

- labs/lab-0/README.md
- labs/lab-7/README.md
Fixed typo, in screenshot it's ping-template, not workshop-template
> Update README.md in lab7

- labs/lab-6/README.md
> Speling eror

- labs/lab-8/README.md
> Correction of spelling

- labs/lab-4/README.md
wildfy_servers -> wildfly_servers
> Spelling error

- labs/lab-2/README.md
- labs/lab-3/README.md
... perhaps more fruitful in the long run due to support for several packaging systems
> - promote package module over yum

- labs/lab-6/README.md
Change `project(repository)` to `project (repository)` and `merge(pull)` to `merge (pull)`.
> Add some spaces

- labs/lab-7/README.md
Clarify where to create the `workshop-playbooks` project
> Clarify lab 7 instructions

- labs/lab-7/README.md
Added: command for launching a job from created job template
> Update README.md: Added job launch command

- labs/lab-0/README.md
Added commands and description on how to verify that $LAB_DIR and $WORK_DIR is pointing to correct directories
> Lab 0: Added commands to verify env variables

- labs/lab-9/README.md
It was either add the port, or change from wildfly1 to loadbalancer1
> wildfly runs on port 8080

- labs/lab-8/README.md
* Removed WORKDIR-assignment, as this is set in bashrc from lab 0
* Added note about privilege escalation
> Minor fixes
